### ISSUE TITLE
Electric return removes all indentation

### ISSUE THREAD

**Issue by NieDzejkob** [kovisoft/paredit#36] opened 2020-07-27 20:09 UTC
When I type `(foo<CR>(bar))`, I get

```
(foo
(bar))
```

instead of

```
(foo
  (bar))
```

It seems that this is because vim removes the trailing indent once the second `<CR>` of the electric return is issued. I have found this workaround:

```
diff --git a/plugin/paredit.vim b/plugin/paredit.vim
index 06fb9c8..76efd46 100644
--- a/plugin/paredit.vim
+++ b/plugin/paredit.vim
@@ -1032,7 +1032,7 @@ function! PareditEnter()
         let pos = col( '.' ) - 1
         if g:paredit_electric_return && pos > 0 && line[pos] =~ b:any_closing_char && !s:InsideString() && s:IsBalanced()
             " Electric Return
-            return "\<CR>\<CR>\<Up>"
+            return "\<CR> \<Backspace>\<CR>\<Up>"
         else
             " Regular Return
             return "\<CR>"
```

However it is imperfect, as pressing enter twice will leave trailing whitespace on the 'empty' line.

**Comment by kovisoft** [comment] 2020-07-29 16:07
Hm, I can't reproduce the problem. For me the test case you described works as intended. If I disable electric return (`let g:paredit_electric_return=0`) and try to simulate what electric return would do, I got this:

- Typing `(foo<CR>` : the cursor is indented below the first 'o`.
- Pressing `<CR>` again: the cursor moves down one line and still indented.
- Pressing `<Up>` : the cursor moves up one line and still indented. And I have two spaces in that line, so the trailing indent is not removed for me.

What vim version are you using? What is your virtualedit setting? (`:set virtualedit?`)

**Comment by NieDzejkob** [comment] 2020-07-29 16:11
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 01 1970 00:00:01)
Included patches: 1-1145
```

`:set virtualedit` responds with `virtualedit=`.

**Comment by kovisoft** [comment] 2020-07-29 16:30
I tried with `set virtualedit=` but for me the result was the same as with other virtualedit settings, however I use vim 8.0.
How about a different approach and change the key order? Could you please replace this:

`return "\<CR>\<CR>\<Up>"`

with this:

`return "\<CR>\<Up>\<End>\<CR>"`

Does it solve the problem or is it still not okay?

**Comment by NieDzejkob** [comment] 2020-07-29 16:41
That's an interesting solution, it does indeed work. I'm curious why our Vims are behaving differently, though. To see exactly what's happening here, I'd suggest enabling `set list listchars=trail:$` - perhaps pressing `<Up>` reintroduces the indent for you?

**Comment by NieDzejkob** [comment] 2020-07-29 16:44
Other possibly relevant setting: for me, `cpoptions=aABceFs`, note the lack of `I`.

**Comment by kovisoft** [comment] 2020-07-29 16:51
Thanks for the test. Whenever I press <CR>, the trailing spaces remain in the line, <Up> does not change this. It may be a difference in our vim versions. Or it may be some other vim options I'm not aware of. I'll try to install vim 8.2 on one of my computers and check how it is behaving.

I have the same cpoptions as you, so it must be something else.

**Comment by NieDzejkob** [comment] 2020-07-29 17:04
This version difference seems to be the culprit: I have tested in `docker run -it debian:stretch` and `docker run -it debian:sid` respectively, to make sure that any custom configuration does not leak in.

In both cases, I tried `apt update && apt install vim`, then `vim test.scm` and `(test)<Left><CR><CR><Up>`. Vim 8.0 left the indentation in place, Vim 8.2 removed it.

**Comment by kovisoft** [comment] 2020-07-29 17:20
Yes, I agree. Actually I found a vim 8.1 on a computer and tested it: it left the trailing spaces in the very first line after `(foo` and in the last line before the closing paren, but removed them from all other lines in between. So it seems that there is no consistent logic here, therefore I'm going to change the key order as above, so that the last key is not the `<Up>` but the `<CR>`, this way the last `<CR>` will add the correct indentation.

Thank you for your kind assistance!

**Comment by kovisoft** [comment] 2020-07-29 20:17
Fixed in commit https://github.com/kovisoft/paredit/commit/c76e0987ec45c84103b408691ec0506e7b99cb30

**Closed** 2020-07-29 21:40 UTC
